export type DomainErrorCode =
  | "CANONICAL_REPOSITORY_READ_ONLY"
  | "REPOSITORY_ARCHIVED"
  | "REPOSITORY_NOT_PUBLIC"
  | "INVALID_FORK_PARENT"
  | "STALE_BRANCH"
  | "INVALID_COMMIT_CONTENT"
  | "INVALID_COMMIT_HASH"
  | "MERGE_FORBIDDEN"
  | "PULL_REQUEST_NOT_OPEN"
  | "MERGE_CONFLICT"
  | "PROVENANCE_REQUIRED"
  | "PROVENANCE_NOT_PUBLIC"
  | "PROVENANCE_URL_INVALID"
  | "REPOSITORY_NOT_FOUND"
  | "REPOSITORY_EXISTS"
  | "BRANCH_NOT_FOUND"
  | "BRANCH_EXISTS"
  | "INVALID_BRANCH_NAME"
  | "COMMIT_NOT_FOUND"
  | "INVALID_DOCUMENT_PATH"
  | "GIT_REPOSITORY_NOT_FOUND"
  | "GIT_OPERATION_FAILED"
  | "COMMIT_METADATA_MISSING"
  | "INVALID_REPOSITORY_SLUG";

export class DomainError extends Error {
  constructor(
    readonly code: DomainErrorCode,
    message: string,
  ) {
    super(message);
    this.name = "DomainError";
  }
}
